# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "flua"
version = "0.1.0"
license = "MIT"
author = "Jiri Furst"
maintainer = "jiri.furst@gmail.com"
copyright = "Copyright 2026, Jiri Furst"
description = "Fortran 95 interface to Lua (luajit-5.1)"
categories = [""]
keywords = ["fortran", "fortran-package-manager"]
homepage = "https://github.com/furstjir/flua"

[build]
   auto-executables = true
   auto-tests = true
   auto-examples = true
   module-naming = false
   link = ["luajit-5.1"]
   
[fortran]
   implicit-typing = false
   implicit-external = false
   source-form = "free"

[install]
   library = false

[dev-dependencies]
   test-drive = {git = "https://github.com/fortran-lang/test-drive" }
